.TH AACPLUSENC 1 "2007-10-11" "1.26" "non-Free High Efficiency Advanced Audio Coder"

.SH NAME
drmplusdemod \- DRM mode E (DRM+) demodulation/decoding library

.SH SYNOPSIS
.B drmplusdemod
.I < infile >
.RI \-o\  <\fIoutfile\fP>
.RI [-s]

.SH DESCRIPTION
.B drmplusdemod
DRM mode E (DRM+) demodulation/decoding library.

.SH FEATURES
.TP
* Portable
.TP
* Fast
.TP
* LC support

.SH OPTIONS
.TP
.BR <\fIinfile\fP>
Set Input wave file, can be "\-", which means stdin.
.TP
.BR \-o\  <\fIoutfile\fP>
Set Output aac file, can be "\-", which means stdout.
.TP

.SH AUTHORS
.TP
Reference: http://www.etsi.org/technologies-clusters/technologies/broadcast/drm
.TP
Wrapper and library code: Sergiy Guriev <simpl@ex.ua>
